title: Peter Reznick - Software Engineer
description: Personal website of Peter Reznick
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://p-reznick.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore 